my_list=[42,43]
my_dict={
    'foo':{
        'a':12,
        'b':(1,2,3,4,my_list)
    },
    'bar':{
        'c':12,
        'd':{5,6,7,8}
    },
    'moo':{
        'e':12,
        'f':{'lol':['l','o','l']}
    },
}
print(my_dict['moo']['f']['lol'])
my_list1=list(my_dict['moo']['f']['lol'])
my_list1.remove('o')
print(my_list1)
new_key={'k':('k','e','k')}
my_dict['moo']['f'].update(new_key)
print(my_dict)
my_dict.clear()
print(my_dict)

